<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>

	  <ApplicationIcon>Resources\RandomCursor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RandomCursor\RandomCursor.csproj" />
	  <Content Include="..\RandomCursor\bin\Debug\net8.0\RandomCursor.exe">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\RandomCursor.ico" />
		<Content Include="Resources\RandomCursor.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

</Project>
