<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>

	  <ApplicationIcon>Resources\RandomCursor.ico</ApplicationIcon>

	  <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

	<ItemGroup>
		<Resource Include="Resources\RandomCursor.ico" />
		<Content Include="Resources\RandomCursor.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RandomCursor\RandomCursor.csproj" />
  </ItemGroup>
</Project>
